# pulled from Teams/hashtags files
terms = [
    'climate change',
    'global warming',
    '#climatechange',
    '#climatestrike',
    '#climate',
    '#greennewdeal',
    '#globalwarming',
    '#climatebrawl',
    '#climatecrisis',
    '#climatehoax',
    '#climateemergency',
    '#climatescam',
    '#gretathunberg', #maybe not this one
    '#climatecult',
    '#greenhypocrisy',
    '#climateaction',
    '#climatetownhall',
    '#climatechangeisreal',
    '#actonclimate',
    '#climateball',
    '#climatemarxism',
    '#AGW',
    '#climatechangethefacts',
    '#peoplesclimate',
    '#climatehustle',
    '#parisagreement',
    '#climatemarch' # basically the max limit of terms we can include..
''' '#youthforclimate',
    '#climatehope',
    '#co2',
    '#climatebreakdown',
    '#riseforclimate',
    '#cleanpowerplan',
    '#climatejustice',
    '#climateweeknyc',
    '#climat', # not a typo
    '#peoplesclimate',
    '#emissions',
    '#carbontax',
    '#stateofclimate',
    '#climateactionnow',
    '#climatescience',
    '#cleanenergyfuture',
    '#peopleofclimate',
    '#nofossilfuelmoney',
    '#coveringclimatenow',
    '#climateuc',
    '#climatechangeisreal',
    '#climatesmart',
    '#startseeingco2',
    '#climatebudget',
    '#netzero',
    '#climatedenial',
    '#climatechanged',
    '#climatefriday',
    '#climatesolutions',
    '#environmentaljustice',
    '#climaterisk',
    '#climateurgency',
    '#climatehkh',
    '#globalclimatestrike',
    '#climatefinance',
    '#oceanforclimate',
    '#climatetutorial',
    '#youthstrike4climate',
    '#climatefacts',
    '#climatesilence',
    '#naturalclimatesolutions',
    '#climatemigration',
    '#climatefact',
    '#climateliability',
    '#climatedisruption',
    '#climatesciencefacts',
    '#endclimatesilence',
    '#changementclimatique',
    '#up4climate',
    '#climatechangethefacts',
    '#climateinsurance',
    '#climatehealth',
    '#climateresilience',
    '#scioclimate',
    '#strike4climate',
    '#unclimatesummit',
    '#climatechangeshealth',
    '#climatetwitter',
    '#climateadaptation',
    '#carbonbudget',
    '#climateservices'
'''
]

# remove duplicate values
query = ' OR '.join(list(set(terms)))[:500]

